apiVersion: apps/v1
kind: Deployment
metadata:
  name: blog-client-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: blog-client
  template:
    metadata:
      labels:
        app: blog-client
    spec:
      containers:
      - name: client
        image: lisandrolan/blog-client
---
apiVersion: v1
kind: Service
metadata:
  name: blog-client-srv
spec:
  type: LoadBalancer
  selector:
    app: blog-client
  ports:
    - name: comments-port
      protocol: TCP
      port: 3000  
      targetPort: 3000