apiVersion: apps/v1
kind: Deployment
metadata:
  name: blog-comments-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: blog-comments
  template:
    metadata:
      labels:
        app: blog-comments
    spec:
      containers:
      - name: comments 
        image: lisandrolan/blog-comments
---
apiVersion: v1
kind: Service
metadata:
  name: blog-comments-srv
spec:
  type: LoadBalancer
  selector:
    app: blog-comments
  ports:
    - name: comments-port
      protocol: TCP
      port: 4001  
      targetPort: 4001