apiVersion: apps/v1
kind: Deployment
metadata:
  name: blog-event-bus-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: blog-event-bus
  template:
    metadata:
      labels:
        app: blog-event-bus
    spec:
      containers:
      - name: blog-event-bus
        image: lisandrolan/blog-event-bus
---
apiVersion: v1
kind: Service
metadata:
  name: blog-event-bus-srv
spec:
  selector:
    app: blog-event-bus
  ports:
    - name: event-bus-port
      protocol: TCP
      port: 4005  
      targetPort: 4005  
