apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-srv
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/use-regex: "true"

spec:
  ingressClassName: nginx
  rules:
    - host: posts.com
      http:
        paths:
          - path: /posts
            pathType: Prefix
            backend:
              service:
                name: blog-query-srv
                port:
                  number: 4002
          - path: /posts/create
            pathType: Prefix
            backend:
              service:
                name: blog-posts-srv
                port:
                  number: 4000
      
          - path: /posts/?(.*)/comments
            pathType: ImplementationSpecific
            backend:
              service:
                name: blog-comments-srv
                port:
                  number: 4001          
          - path: /?(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: blog-client-srv
                port:
                  number: 3000