apiVersion: apps/v1
kind: Deployment
metadata:
  name: blog-moderation-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: blog-moderation
  template:
    metadata:
      labels:
        app: blog-moderation
    spec:
      containers:
      - name: moderation 
        image: lisandrolan/blog-moderation
---
apiVersion: v1
kind: Service
metadata:
  name: blog-moderation-srv
spec:
  type: LoadBalancer
  selector:
    app: blog-moderation
  ports:
    - name: moderation-port
      protocol: TCP
      port: 4002  
      targetPort: 4002